services:
  db:
    image: mysql:latest
    container_name: express-mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer_db
    volumes:
      - ~/mysql-data/db:/var/lib/mysql
